function output = JRcarb2mat(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, VELOCITY, STATE, DISP, STRESS, LNVELOCITY] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TIME, VELOCITY, STATE, DISP, STRESS, LNVELOCITY] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Time, Velocity, State, Disp, Stress, lnVelocity] = importfile("G:\My Drive\Stefano\Ricerca\Collaborations\2020_FEAR\fluid injection SHIVA BRAVA\jr_model\zenodo-repo\Carbonate08ss_injection_rate_02_alpha_00.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Mar-2024 12:41:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "Velocity", "State", "Disp", "Stress", "lnVelocity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
output(:,1) = tbl.Time;
output(:,2) = tbl.Velocity;
output(:,3) = tbl.State;
output(:,4) = tbl.Disp;
output(:,5) = tbl.Stress;
output(:,6) = zeros(size(tbl.Time,1),1); %porosity
output(:,7) = zeros(size(tbl.Time,1),1);%prev
output(:,8) = zeros(size(tbl.Time,1),1);%p

end