function output = JRshale2mat(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIMESHIFTED, VELOCITY, STATE, DISP, STRESS, POROSITY, PREV, PSLIP,
%  LNVELOCITY, TIMESCALED, TIMEMIN, VELOCITYMMS, DISPMICRONS] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TIMESHIFTED, VELOCITY, STATE, DISP, STRESS, POROSITY, PREV, PSLIP,
%  LNVELOCITY, TIMESCALED, TIMEMIN, VELOCITYMMS, DISPMICRONS] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [TimeShifted, Velocity, State, Disp, Stress, Porosity, Prev, Pslip, lnVelocity, TimeScaled, Timemin, Velocitymms, Dispmicrons] = importfile("G:\My Drive\Stefano\Ricerca\Collaborations\2020_FEAR\fluid injection SHIVA BRAVA\jr_model\zenodo-repo\Shale08ss_injection_rate_02_alpha_02.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Mar-2024 12:50:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimeShifted", "Velocity", "State", "Disp", "Stress", "Porosity", "Prev", "Pslip", "lnVelocity", "TimeScaled", "Timemin", "Velocitymms", "Dispmicrons"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type

output(:,1) = tbl.TimeShifted-tbl.TimeShifted(1);
output(:,2) = tbl.Velocity;
output(:,3) = tbl.State;
output(:,4) = tbl.Disp;
output(:,5) = tbl.Stress;
output(:,6) = tbl.Porosity;
output(:,7) = tbl.Prev;
output(:,8) = tbl.Pslip;
end